//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamesRiverHBC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipDue
    {
        public decimal TransactionId { get; set; }
        public decimal ClubYear { get; set; }
        public string TXN_ID { get; set; }
        public string PayPalStatus { get; set; }
        public string PayPalInvoice { get; set; }
        public bool Paid { get; set; }
        public System.DateTime DateEntered { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public string Comment { get; set; }
        public int MemberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
